import "./styles.css";
import borgirImg from "./borgir.jpg";
console.log("Esta todo andando");
// Elements that contains other elements
export const content = document.getElementById("content");
const restInfo = document.createElement("div");
const imgContainer = document.createElement("div");
const deals = document.createElement("div");
// Elements inside of elements generated by me
const image = document.createElement("img");
const restName = document.createElement("div");
const restDesc = document.createElement("div");
const dealsTitle = document.createElement("div");
const dealsDesc = document.createElement("div");

// Adding classes to all generated elements
restInfo.classList.add("info", "card");
imgContainer.classList.add("img-container", "card");
deals.classList.add("deals", "card");
restName.classList.add("name");
restDesc.classList.add("description");
dealsTitle.classList.add("title", "deals");
dealsDesc.classList.add("description", "deals");

// Appending childs to the corresponding father
content.append(restInfo, imgContainer, deals);
restInfo.append(restName, restDesc);
imgContainer.appendChild(image);
deals.append(dealsTitle, dealsDesc);

// Setting up elements
image.src = borgirImg;
restName.textContent = "Borgir";
restDesc.textContent =
  "An established fast-food chain, where only the best Borgir's are made";
dealsTitle.textContent = "BOGO on cheesy Borgir's";
dealsDesc.textContent = "Buy one get one free on Borgir's with cheese on them";

// function that deletes all child nodes from content div
// google a better way to do this
export function removeChilds() {
  while (content.hasChildNodes()) {
    content.removeChild(content.lastChild);
  }
}
